'use client';

import { ChangeEvent, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { FileCode2, UploadCloud } from 'lucide-react';
import {
  artifactKinds,
  type ArtifactKind,
  type ArtifactVisibility,
  type PublishResult,
  visibilityOptions,
} from '@docscn/sdk';
import { Badge, Button, Card, Eyebrow, Shell } from '@docscn/ui';

const starterHtml = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { margin: 0; font-family: ui-sans-serif, system-ui; background: #09090b; color: #fafafa; }
      main { padding: 40px; }
      .card { border: 1px solid #3f3f46; border-radius: 24px; padding: 24px; background: #18181b; }
      button { border: 0; border-radius: 12px; padding: 12px 16px; background: #5eead4; color: #042f2e; font-weight: 800; }
    </style>
  </head>
  <body>
    <main>
      <p>agent-generated artifact</p>
      <div class="card">
        <h1>Interactive launch plan</h1>
        <p>This self-contained HTML can include layout, charts, SVG, and small scripts.</p>
        <button onclick="alert('docscn keeps this inside a sandboxed artifact frame')">Try interaction</button>
      </div>
    </main>
  </body>
</html>`;

export function PublishArtifactForm() {
  const router = useRouter();
  const [title, setTitle] = useState('Interactive launch plan from agent');
  const [description, setDescription] = useState(
    'A self-contained HTML artifact generated by an agent and ready for team review.',
  );
  const [authorName, setAuthorName] = useState('Cursor agent');
  const [visibility, setVisibility] = useState<ArtifactVisibility>('unlisted');
  const [kind, setKind] = useState<ArtifactKind>('custom-html');
  const [html, setHtml] = useState(starterHtml);
  const [isPublishing, setIsPublishing] = useState(false);
  const [error, setError] = useState<string | undefined>();

  const canPublish = useMemo(
    () =>
      title.trim().length > 0 &&
      description.trim().length > 0 &&
      html.includes('<html'),
    [description, html, title],
  );

  async function publish() {
    if (!canPublish) {
      return;
    }

    setIsPublishing(true);
    setError(undefined);

    try {
      const response = await fetch('/api/artifacts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title,
          description,
          html,
          visibility,
          authorName,
          source: 'web',
          kind,
        }),
      });

      if (!response.ok) {
        throw new Error('Artifact publish failed.');
      }

      const payload = (await response.json()) as { result: PublishResult };
      router.push(payload.result.url);
      router.refresh();
    } catch (publishError) {
      setError(
        publishError instanceof Error
          ? publishError.message
          : 'Artifact publish failed.',
      );
    } finally {
      setIsPublishing(false);
    }
  }

  async function handleUpload(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) {
      return;
    }

    setHtml(await file.text());
    if (!title.trim()) {
      setTitle(file.name.replace(/\.html?$/i, ''));
    }
  }

  return (
    <Shell className="grid gap-8 py-10 lg:grid-cols-[0.9fr_1.1fr]">
      <div className="space-y-6">
        <div>
          <Eyebrow>publish artifact</Eyebrow>
          <h1 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">
            Turn agent output into a reviewable interactive page.
          </h1>
          <p className="mt-4 text-muted-foreground">
            Paste or upload self-contained HTML. docscn creates a shareable
            artifact page with metadata, visibility, review threads, and
            revision history ready to grow into API and CLI publishing.
          </p>
        </div>
        <Card className="p-5">
          <div className="flex items-center gap-3">
            <FileCode2 className="h-5 w-5 text-primary" />
            <div>
              <p className="font-medium">Future CLI shape</p>
              <p className="font-mono text-sm text-muted-foreground">
                npx docscn publish artifact.html
              </p>
            </div>
          </div>
        </Card>
      </div>

      <Card className="space-y-5 p-6">
        <div className="grid gap-4 md:grid-cols-2">
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Title</span>
            <input
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none ring-ring focus:ring-2"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
            />
          </label>
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Author / agent</span>
            <input
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none ring-ring focus:ring-2"
              value={authorName}
              onChange={(event) => setAuthorName(event.target.value)}
            />
          </label>
        </div>

        <label className="space-y-2 text-sm">
          <span className="text-muted-foreground">Description</span>
          <textarea
            className="min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none ring-ring focus:ring-2"
            value={description}
            onChange={(event) => setDescription(event.target.value)}
          />
        </label>

        <div className="grid gap-4 md:grid-cols-2">
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Visibility</span>
            <select
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none ring-ring focus:ring-2"
              value={visibility}
              onChange={(event) =>
                setVisibility(event.target.value as ArtifactVisibility)
              }
            >
              {visibilityOptions.map((option) => (
                <option key={option}>{option}</option>
              ))}
            </select>
          </label>
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Artifact type</span>
            <select
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none ring-ring focus:ring-2"
              value={kind}
              onChange={(event) => setKind(event.target.value as ArtifactKind)}
            >
              {artifactKinds.map((option) => (
                <option key={option}>{option}</option>
              ))}
            </select>
          </label>
        </div>

        <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-dashed border-border bg-secondary/40 p-4 text-sm">
          <span className="flex items-center gap-3 text-muted-foreground">
            <UploadCloud className="h-5 w-5 text-primary" />
            Upload a self-contained HTML file
          </span>
          <Badge tone="outline">optional</Badge>
          <input
            className="sr-only"
            type="file"
            accept=".html,.htm"
            onChange={handleUpload}
          />
        </label>

        <label className="space-y-2 text-sm">
          <span className="text-muted-foreground">Self-contained HTML</span>
          <textarea
            className="min-h-80 w-full rounded-md border border-input bg-background px-3 py-2 font-mono text-xs outline-none ring-ring focus:ring-2"
            value={html}
            onChange={(event) => setHtml(event.target.value)}
          />
        </label>

        {error ? (
          <p className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </p>
        ) : null}

        <Button
          className="w-full"
          disabled={!canPublish || isPublishing}
          size="lg"
          onClick={publish}
        >
          {isPublishing
            ? 'Publishing artifact...'
            : 'Generate shareable artifact page'}
        </Button>
      </Card>
    </Shell>
  );
}
