'use client';

import Link from 'next/link';
import { ChangeEvent, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { BookOpenText, TerminalSquare, UploadCloud } from 'lucide-react';
import {
  artifactKinds,
  type ArtifactKind,
  type ArtifactVisibility,
  type PublishResult,
  visibilityOptions,
} from '@docscn/sdk';
import { Badge, Button, Card, Shell } from '@docscn/ui';
import { saveAnonymousClaimReceipt } from '../lib/anonymous-claim-receipts';
import { AppPageHeader } from './app-page-header';

const starterHtml = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { margin: 0; font-family: ui-sans-serif, system-ui; background: #09090b; color: #fafafa; }
      main { padding: 40px; }
      .card { border: 1px solid #3f3f46; border-radius: 24px; padding: 24px; background: #18181b; }
      button { border: 0; border-radius: 12px; padding: 12px 16px; background: #2563eb; color: #ffffff; font-weight: 800; }
    </style>
  </head>
  <body>
    <main>
      <p>agent-generated artifact</p>
      <div class="card">
        <h1>Interactive launch plan</h1>
        <p>This self-contained HTML can include layout, charts, SVG, and small scripts.</p>
        <button onclick="alert('docscn keeps this inside a sandboxed artifact frame')">Try interaction</button>
      </div>
    </main>
  </body>
</html>`;

export function PublishArtifactForm({
  isAuthenticated,
}: {
  isAuthenticated: boolean;
}) {
  const router = useRouter();
  const [title, setTitle] = useState('Interactive launch plan from agent');
  const [description, setDescription] = useState(
    'A self-contained HTML artifact generated by an agent and ready for team review.',
  );
  const [authorName, setAuthorName] = useState('Cursor agent');
  const [visibility, setVisibility] = useState<ArtifactVisibility>('unlisted');
  const [kind, setKind] = useState<ArtifactKind>('custom-html');
  const [html, setHtml] = useState(starterHtml);
  const [isPublishing, setIsPublishing] = useState(false);
  const [error, setError] = useState<string | undefined>();

  const availableVisibilityOptions = isAuthenticated
    ? visibilityOptions
    : visibilityOptions.filter((option) => option === 'unlisted');

  const canPublish = useMemo(
    () =>
      title.trim().length > 0 &&
      description.trim().length > 0 &&
      html.includes('<html'),
    [description, html, title],
  );

  async function publish() {
    if (!canPublish) {
      return;
    }

    setIsPublishing(true);
    setError(undefined);

    try {
      const response = await fetch('/api/artifacts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title,
          description,
          html,
          visibility,
          authorName,
          source: 'web',
          kind,
        }),
      });

      if (!response.ok) {
        throw new Error('Artifact publish failed.');
      }

      const payload = (await response.json()) as { result: PublishResult };
      if (!isAuthenticated && payload.result.claimToken) {
        saveAnonymousClaimReceipt({
          artifactId: payload.result.artifactId,
          slug: payload.result.slug,
          title,
          claimToken: payload.result.claimToken,
          createdAt: new Date().toISOString(),
        });
      }
      router.push(payload.result.url);
      router.refresh();
    } catch (publishError) {
      setError(
        publishError instanceof Error
          ? publishError.message
          : 'Artifact publish failed.',
      );
    } finally {
      setIsPublishing(false);
    }
  }

  async function handleUpload(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) {
      return;
    }

    setHtml(await file.text());
    if (!title.trim()) {
      setTitle(file.name.replace(/\.html?$/i, ''));
    }
  }

  return (
    <Shell className="grid gap-8 py-10 lg:grid-cols-[0.88fr_1.12fr]">
      <div className="space-y-6">
        <AppPageHeader
          actions={
            <>
              <Button asChild>
                <a href="/skills.md">Open skills.md</a>
              </Button>
              <Button asChild variant="outline">
                <Link href="/settings/api-keys">API keys</Link>
              </Button>
            </>
          }
          description={
            isAuthenticated
              ? 'The happy path is agent or CLI publishing. Keep this form for smoke tests, demos, and one-off uploads.'
              : 'Anonymous publishes are unlisted, view-only links. Sign in when you want comments, revisions, analytics, private sharing, and artifact ownership.'
          }
          eyebrow={
            isAuthenticated ? 'agent publishing first' : 'instant publish'
          }
          title={
            isAuthenticated
              ? 'Point agents at the CLI and skills.md.'
              : 'Publish an artifact now. No account required.'
          }
        />
        <Card className="space-y-5 p-5">
          <div className="flex items-start gap-3">
            <TerminalSquare className="mt-0.5 h-5 w-5 text-primary" />
            <div className="min-w-0">
              <p className="font-medium">Preferred path: CLI publish</p>
              <p className="mt-1 text-sm leading-6 text-muted-foreground">
                Install once, sign in from the terminal, then let Cursor,
                Claude, scheduled jobs, and MCP workflows publish artifacts
                without touching this form.
              </p>
              <code className="app-code-panel mt-3 block overflow-x-auto rounded-xl p-3 font-mono text-xs text-foreground">
                curl /install -fsS | bash
                <br />
                docscn login
                <br />
                docscn publish artifact.html
              </code>
            </div>
          </div>
          <div className="flex items-start gap-3 border-t border-border pt-5">
            <BookOpenText className="mt-0.5 h-5 w-5 text-primary" />
            <div>
              <p className="font-medium">Agent instructions</p>
              <p className="mt-1 text-sm leading-6 text-muted-foreground">
                Give agents{' '}
                <a className="text-primary hover:underline" href="/skills.md">
                  /skills.md
                </a>{' '}
                so they know how to publish, read feedback, and submit
                revisions.
              </p>
            </div>
          </div>
        </Card>
      </div>

      <Card className="space-y-5 p-6">
        <div>
          <p className="home-sheet-label">manual upload fallback</p>
          <h2 className="mt-2 font-display text-2xl font-semibold tracking-tight">
            Paste or upload HTML.
          </h2>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">
            Useful for local smoke tests and one-off artifacts when an agent is
            not driving the workflow.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Title</span>
            <input
              className="app-field w-full rounded-md px-3 py-2 text-sm"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
            />
          </label>
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Author / agent</span>
            <input
              className="app-field w-full rounded-md px-3 py-2 text-sm"
              value={authorName}
              onChange={(event) => setAuthorName(event.target.value)}
            />
          </label>
        </div>

        <label className="space-y-2 text-sm">
          <span className="text-muted-foreground">Description</span>
          <textarea
            className="app-field min-h-24 w-full rounded-md px-3 py-2 text-sm"
            value={description}
            onChange={(event) => setDescription(event.target.value)}
          />
        </label>

        <div className="grid gap-4 md:grid-cols-2">
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Visibility</span>
            <select
              className="app-field w-full rounded-md px-3 py-2 text-sm"
              value={visibility}
              onChange={(event) =>
                setVisibility(event.target.value as ArtifactVisibility)
              }
            >
              {availableVisibilityOptions.map((option) => (
                <option key={option}>{option}</option>
              ))}
            </select>
            {!isAuthenticated ? (
              <span className="block text-xs leading-5 text-muted-foreground">
                Anonymous artifacts are always unlisted. Sign in for private or
                public ownership controls.
              </span>
            ) : null}
          </label>
          <label className="space-y-2 text-sm">
            <span className="text-muted-foreground">Artifact type</span>
            <select
              className="app-field w-full rounded-md px-3 py-2 text-sm"
              value={kind}
              onChange={(event) => setKind(event.target.value as ArtifactKind)}
            >
              {artifactKinds.map((option) => (
                <option key={option}>{option}</option>
              ))}
            </select>
          </label>
        </div>

        <label className="app-code-panel flex cursor-pointer items-center justify-between gap-4 rounded-xl border-dashed p-4 text-sm">
          <span className="flex items-center gap-3 text-muted-foreground">
            <UploadCloud className="h-5 w-5 text-primary" />
            Upload a self-contained HTML file
          </span>
          <Badge tone="outline">optional</Badge>
          <input
            className="sr-only"
            type="file"
            accept=".html,.htm"
            onChange={handleUpload}
          />
        </label>

        <label className="space-y-2 text-sm">
          <span className="text-muted-foreground">Self-contained HTML</span>
          <textarea
            className="app-field min-h-80 w-full rounded-md px-3 py-2 font-mono text-xs"
            value={html}
            onChange={(event) => setHtml(event.target.value)}
          />
        </label>

        {error ? (
          <p className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </p>
        ) : null}

        <Button
          className="w-full"
          disabled={!canPublish || isPublishing}
          size="lg"
          onClick={publish}
        >
          {isPublishing
            ? 'Publishing artifact...'
            : isAuthenticated
              ? 'Generate shareable artifact page'
              : 'Publish unlisted artifact'}
        </Button>
      </Card>
    </Shell>
  );
}
